services:
  - type: web
    name: maintenance-dispatch-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_ALLOWED_HOSTS
        value: "maintenance-dispatch-backend.onrender.com"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "False"

